### ISSUE TITLE
Julia 1.0

### ISSUE THREAD

**Issue by cortner** [libAtoms/JuLIP.jl#101]
0.7=1.0 Alpha has just been released

https://github.com/JuliaLang/julia/blob/master/NEWS.md

I want to move over the JuLIP ecosystem as quickly as possible, and at the same time move also to Python 3

**Comment by jameskermode** [comment]
Sounds good. I see that the dot overloading issue has been fixed, so using Python libraries from Julia will feel more comfortable. 

One problem with moving to Py3 is that quip(py) doesn’t support it yet, but this is becoming increasingly urgent so I will need to fix it this summer.

**Comment by cortner** [comment]
Here an initial list of key dependencies, this is a subset of REQUIRE, I left out some that could initially be dropped.

StaticArrays
Optim 0.14
Calculus 0.2 0.3-
FunctionWrappers
Dierckx 0.3 0.4-
MacroTools

**Comment by cortner** [comment]
Dierckx actually *mostly* works as well
