### ISSUE TITLE
Create DerivTest.jl based on Testing.jl ?

### ISSUE THREAD

**Issue by pkofod** [libAtoms/JuLIP.jl#112]
Based on the discussion in https://github.com/JuliaNLSolvers/Optim.jl/issues/386, would it make sense to extract the code in Testing.jl to a small package? I promise to help maintain it, but you can keep it wherever you want.

**Comment by cortner** [comment]
Sure - why not . FiniteDifferenceTests.jl ?

**Comment by pkofod** [comment]
That sounds fine, unless someone might mistake that for a package used for testing finite difference packages like Calculus or DiffEqDiffTools..

**Comment by cortner** [comment]
Any suggestions?

**Comment by pkofod** [comment]
DerivativeTests.jl? You could potentially test against AD as well If you where worried if your hand-written-to-be-maximally-performant-even-If-AD-World version was correct.

**Comment by cortner** [comment]
Sounds good

**Comment by cortner** [comment]
Gives me a chance to learn how to use the new package registration system. I’ll do this ASAP and give you push access

**Comment by cortner** [comment]
I guess this is closed with [https://github.com/cortner/DerivativeTests.jl](https://github.com/cortner/DerivativeTests.jl)

**Comment by pkofod** [comment]
> Gives me a chance to learn how to use the new package registration system. I’ll do this ASAP and give you push access

I also need to do that... :)
