### ISSUE TITLE
Julia Calculator in ASE

### ISSUE THREAD

**Issue by cortner** [libAtoms/JuLIP.jl#12]
create a python module that implements a JuliaCalculator  or JulipCalculator from ASE

**Comment by cortner** [comment]
should this be in JuLIP or in ASE?

**Comment by jameskermode** [comment]
ASE, eventually - same as any other interface to external calculators, which they are happy to host. I will start with a module in JuLIP/temp, to iron out the bugs.

**Comment by gabor1** [comment]
although we have a fork of ASE through James, how good is the track record of merging changes back to the trunk of ASE? I'm worried about too much deviation.  

— Gábor

**Comment by jameskermode** [comment]
agreed - I think it's better to submit things to ASE little and often. we're getting there with the main preconditioner pull request, which is now submitted for review (but I still need to write some documentation before they will accept it).

**Comment by cortner** [comment]
given that nobody would use it who doesn't use JuLIP, why not have a Python module bundled with JuLIP and provide an installation mechanism?

**Comment by jameskermode** [comment]
Point of getting it in ASE would be for wider dissemination - would get logo on their webpage, etc.

**Comment by tdaff** [comment]
From my experience, ase are very active at merging contributions now that they are on GitLab. Sensible bugfixes are usually merged within a day.

-- Tom

**Comment by jameskermode** [comment]
I just pushed pull request #15 with a first attempt at this. It creates the JuLIP calculator from an arbitrary string of Julia code, and then works as a standard ASE calculator. So far only energy and forces are supported - I don't think there's any support for stress or virials in JuLIP yet.
