### ISSUE TITLE
`grad` and `gradient`

### ISSUE THREAD

**Issue by cortner** [libAtoms/JuLIP.jl#13]
Since making a `Potential` a calculator, JuLIP got confused about what `grad` means. It can mean either `- forces` or it can mean `evaluate_d * R/r`. I suggest to rename `-forces = gradient` and keep `grad = evaluate_d * R/r` (or similar usage).

**Comment by cortner** [comment]
should this be in JuLIP or in ASE?

**Comment by gabor1** [comment]
I agree, "gradient" should mean "-forces", and grad should remain the operator

— Gábor

**Comment by cortner** [comment]
I am now thinking to use gradient as the gradient with respect to all degrees of freedom, e.g., 
* for a fixed cell with no clamped atoms it would be just -forces
* for a variable cell with no clamped atoms it would be [-forces; stress]

Does this seem natural to you? 

I am thinking to either completely remove the usage of gradient as - forces (without reference to which cell constraint used)  or renaming it to `negforces` or something similar.

**Comment by jameskermode** [comment]
Yes, I agree this is the natural usage of gradient() in the general case.

**Comment by cortner** [comment]
#18
