### ISSUE TITLE
Automatic Differentiation

### ISSUE THREAD

**Issue by cortner** [libAtoms/JuLIP.jl#17]
`ReverseDiffSource` will never be able to resolve the complex layers of function calls, but in particular the neighbourlist. The most likely candidates for more general usage of AD are `ReverseDiffPrototype.jl` and `Autodiff.jl`. But those (as well as `ForwardDiff`) require generic types instead of `Float64` being hard-coded. So to take advantage of AD packages some fairly serious rewriting is needed unfortunately.

**Comment by jameskermode** [comment]
For many applications (i.e. whenever the potential has a cutoff and no new bonds will ever be formed) the neighbourlist can be frozen for AD purposes. Then `ReverseDiffSource` remains an option.

**Comment by cortner** [comment]
Ok good to know. Then I'll play at some point with extending RDS to static arrays.

**Comment by cortner** [comment]
I always thought that `ReverseDiffSource` needs a fixed dimension, but this looks pretty promising: 
```
julia> ex = rdiff( :( sum( x.^2 ) ), x=rand(10) )
quote
    _tmp1 = x .^ 2
    _tmp2 = size(_tmp1)
    (sum(_tmp1),zeros(size(x)) + (2x) .* (zeros(_tmp2) + ones(_tmp2)))
end
```

**Comment by cortner** [comment]
[ReverseDiffSource.jl](https://github.com/JuliaDiff/ReverseDiffSource.jl) definitely now supports variable length inputs. 

* [ ] fix JuLIP to be able to ReverseDiffSource differentiate *all* potentials
* [ ] test performance of automatic versus manual 
* [ ] probably rewrite all potentials to use ReverseDiffSource.

Main problem with ReverseDiffSource is that it does not support "inner" function calls. For that, see XDiff.jl, but the latter doesn't support loops.

**Comment by cortner** [comment]
ReverseDiffSource and XDiff are too fragile. I've put ForwarDiff potentials back in. Maybe I'll revisit this after RDS and XD have been updated to J v1.0.
