### ISSUE TITLE
Fix Implementation of Pressure

### ISSUE THREAD

**Issue by cortner** [libAtoms/JuLIP.jl#26]
Right now, I've written energy as 
```
   energy <- energy - pressure * det( defm(at) ) 
```
which is surely wrong, since there should be some form of normalisation against size of the of the cell; deformed / undeformed maybe? But what does this mean here? 

I looked in ASE, but there doesn't seem to be any pressure option in the `UnitCellFilter`?

CC @jameskermode

**Comment by jameskermode** [comment]
Controlling the pressure is not yet implemented in ASE - that's partly why we're motivated to play with it here. It is implemented in QUIP, and we use exactly this enthalpy function, with no further normalisation.

https://github.com/libAtoms/QUIP/blob/public/src/Potentials/Potential.f95#L1647

**Comment by jameskermode** [comment]
There is a sign error currently: here is the pressure/volume curve for SW silicon.  By convention, compression should correspond to positive pressure. The gradient is related to the bulk modulus - absolute value does come out correctly. Enthalpy should be `H = E + pV`, not `E - pV` as currently. I'll check in the fix.

![f7afqu2t9vn2rvreeonn8jly2pnmjucohda 61cezk8lmzwfwoiiiiiyd mfswrererkylgiyiiijhmauteretezapyiiiiiiztwbirerexmqkwiiiiimn by1fynqwux6aaaaaaelftksuqmcc](https://cloud.githubusercontent.com/assets/1049932/19311138/52445e32-908d-11e6-9f2e-e43f7105d365.png)

**Comment by cortner** [comment]
I assume this is fixed now.
