### ISSUE TITLE
adsite.jl not found

### ISSUE THREAD

**Issue by git4lei** [libAtoms/JuLIP.jl#27]
WARNING: adsite.jl could not be included; most likely some AD package is missing;
at the moment it needs `ForwardDiff, ReverseDiffPrototype`
In [3]:

**Comment by cortner** [comment]
now looks like I just need to improve the documentation; or even turn this off altogether.

**Comment by git4lei** [comment]
Yes, there is no error now.
Lei

**Comment by cortner** [comment]
I've turned off the warning for now (and will keep it off until I implement AD properly)
