### ISSUE TITLE
Visualisation

### ISSUE THREAD

**Issue by cortner** [libAtoms/JuLIP.jl#3]
Either 

* Implement minimalistic visualisation using `ThreeJS` and/or `GLVisualise`

or 

* get `chemview` to work under Julia

**Comment by jameskermode** [comment]
AtomEye is another option. My fork at https://github.com/jameskermode/atomeye can be popped open from a notebook, so would only require a minimal amount of work to use it from JuLIP (essentially a JuLIP -> ASE Atoms converter, which may already exist)

**Comment by tdaff** [comment]
I've used https://github.com/patrickfuller/imolecule and http://wiki.jmol.org/index.php/JSmol for embedded web viewers in the past. They might require some fiddling.

**Comment by cortner** [comment]
@tdaff  do you have a python code that passes positions and bonds directly to either of these? Or is the idea to write configurations as `.xyz` and then load?

**Comment by gabor1** [comment]
I'm using imolecule from julia, it doesn't have a lot of features (basically none) but is very fast and compact. see the bits and pieces attached script (it used to be in the Notebooks folder of the Atoms.jl git repo, and there are notebooks there that use it)



— Gábor

**Comment by cortner** [comment]
@jameskermode `atomeye` seems to depend on `libatoms`?
```
./atomeyelib.h:9:10: fatal error: 'libatoms.h' file not found
```
(on running `make atomeyelib`)

**Comment by cortner** [comment]
I just wasted over an hour trying to install `pybel`. Why can't a sophisticated library like Open Babel not have a simple `pip install openbabel` option (they actually do, but it is broken)

**Comment by cortner** [comment]
```
In [1]: import pybel
Fatal Python error: PyThreadState_Get: no current thread
/Users/ortner/anaconda/bin/python.app: line 3: 62834 Abort trap: 6           /Users/ortner/anaconda/python.app/Contents/MacOS/python "$@"
```
@gabor1 Any idea at all?

**Comment by gabor1** [comment]
yeah I had some trouble installing pybel. (but not this one). I went through the various options, macports, pip, github, etc. one of them worked.  

— Gábor

**Comment by jameskermode** [comment]
Yes, AtomEye depends on QUIP for .xyz reading and I think for the Python interface too. Hopefully the README describes this correctly.

**Comment by cortner** [comment]
unfortunately it isn't really an option for JuLIP then; QUIP isn't exactly an automatic install.

**Comment by jameskermode** [comment]
Should be easy enough to make it useable without QUIP - it's one .c and one .h file so wouldn't be hard to repackage.

**Comment by cortner** [comment]
ok, if I fail with `imolecule`  then I'll get back to that.

**Comment by cortner** [comment]
ok - managed to install ok and not cause a crash, but next: 
```python
/Users/ortner/anaconda/lib/python2.7/site-packages/pybel.py in <module>()
     87 _builder = ob.OBBuilder()
     88
---> 89 informats = _formatstodict(_obconv.GetSupportedInputFormat())
     90 """A dictionary of supported input formats"""
     91 outformats = _formatstodict(_obconv.GetSupportedOutputFormat())

/Users/ortner/anaconda/lib/python2.7/site-packages/pybel.py in _formatstodict(list)
     66     broken = [x.replace("[Read-only]", "").replace("[Write-only]", "").split(
     67               " -- ") for x in list]
---> 68     broken = [(x, y.strip()) for x, y in broken]
     69     return dict(broken)
     70
```
Can anybody who is more used to Python suggest what this could be?

**Comment by cortner** [comment]
Update: imolecuke works now.

**Comment by cortner** [comment]
@jameskermode `imolecule` doesn't always get the bonds right - can I define a list of bonds in ASE.io.write?

**Comment by gabor1** [comment]
If you use the cif writer, there ought to be a way to communicate the bonds but you might have to write your own function that takes the connectivity info

-- Gábor

**Comment by jameskermode** [comment]
The matscipy chemview interface builds list of bonds from neighbour list. This works pretty well for me with relatively small systems.

**Comment by cortner** [comment]
Chemview is difficult to get to run from Julia, maybe not an option

**Comment by cortner** [comment]
Got an initial implementation workin. Thank you all.
