### ISSUE TITLE
DOF Managers and Molecular Dynamics

### ISSUE THREAD

**Issue by cortner** [libAtoms/JuLIP.jl#32]
It occurred to me that #20 would also lead to a natural way to incorporate dynamics into the framework. The idea would be to define (e.g.) a `Dynamics <: DofManager` (ignoring cell shape dynamics for now) which returns 

```
  dofs(at) = [positions[:]; momenta[:]] 
```

as opposed to what happens at the moment

```
 dofs(at) = positions[:]
```

**Comment by cortner** [comment]
A small risk with locking ourselves into the ASE structure of `positions` and `momenta` is that generalisations could become more complicated to implement. E.g., suppose we want some higher-dimensional dynamics such as the "Nose-Hoover-Langevin" or similar. Then we'd need additional variables and hence a new DOF manager. Probably #28 will help, but maybe the DofManager could be defined from the beginning in such a way that it deals with an arbitrary number of unknowns for each site?

**Comment by jameskermode** [comment]
> One possibility would be to reserve keys :p and :q and have the general get_array, set_array! from #28 redirect those to *et_positions and *et_momenta?

This is exactly what ASE does, although with keys "positions" and "momenta".

**Comment by cortner** [comment]
ok - perfect.

**Comment by cortner** [comment]
`position_dofs`, `momenta_dofs` ?

**Comment by cortner** [comment]
Related issue: do we interface ASE's Trajectory functionality, or will it be easier to just rewrite this in pure Julia? The documentation isn't so clear about how to use it and skimming through the code it is quite convoluted. Personally I'd prefer to get access to it via `push!`, `append!`, etc.

**Comment by jameskermode** [comment]
I'm not a big fan of the ASE trajectory format, so happy to rewrite. A key consideration is how to deal with very large files which cannot be read entirely into memory - this is where complexity comes in. The NetCDFTrajectory in ASE deals with this nicely.

I suggest we start by interfacing to ``ase.io.read(filename, format)`` and ``ase.io.write(filename, atoms, format)`` for single-configuration I/O in various formats as that will be slow/painful to rewrite.

**Comment by cortner** [comment]
To get something up and running, would it be sufficient to just define a directory, and to write .xyz files with increasing numbers after each call to `push!` (or something like that)? I need to go and check what OVITO can read.

**Comment by jameskermode** [comment]
You can simply concat multiple frames to a single xyz file. Ovito can read that, because I implemented it :-)

**Comment by cortner** [comment]
How do you do this in ASE?

**Comment by jameskermode** [comment]
Pass an open file handle to ``ase.io.write()`` instead of a filename:

```python
import ase.io

fh = open("big.xyz", "w")
for at in list_of_atoms:
    ase.io.write(fh, at)
fh.close()
```

**Comment by cortner** [comment]
* Presumably this would also work with "a"?
* What is a typical limit for this format? Say with 10k atoms, then how many snapshot could I store before it becomes impractical?

**Comment by jameskermode** [comment]
Yes, you can also append to existing files. I'm ashamed to admit I've used this format for thousands of timesteps with ~10^5 atoms, i.e. 100 Gb filesizes. It does become a bit impractical at that point, which I offset in QUIP by building an ``.xyz.idx`` index file that lives alongside the ``.xyz`` and allows random access to frames; but this is a nasty hack that I would rather leave behind. 

Making a subdirectory to store sequentially numbered files (``frame00001.xyz``, etc.) may be a better solution (and is also supported by OVITO).

If we are willing to introduce an additional dependency, the NetCDF trajectory format implemented in ASE is now also supported by VMD, LAMMPS and OVITO. NetCDF classical (v3) files are more fault tolerant than v4+, which is built on hdf5.

**Comment by gabor1** [comment]
Just chiming in: we've had an _excellent_ run with the .xyz files, and 
the associated .idx files. They've served us well for 10 years, coped 
with all sorts of extensions and tightening up of the specs. It would be 
a real shame to lose them. I like the way you can almost forget about 
the .idx file, it gets regenerated automatically, you can delete them at 
will, etc. it would be horrible to _have_ to carry around directories. 
Never mind the  fact that "ls" fails if there are too many files. There 
were cases where I simply could not work with someone's data because it 
came as a directory. I also use NetCDF when I expect the file to be 
huge, and it's a nice format if large things. the disadvantage is that 
you can't inspect the file quickly (i.e. with "less")

Let's please have a discussion.

**Comment by jameskermode** [comment]
Good points, definitely good to discuss in light of our experiences with QUIP. 

How about storing xyz frames in a (gzipped) tarball, so the index lives with the data? This would allow efficient random access, and could then still inspect with standard tools.

**Comment by gabor1** [comment]
CAn you easily append to that?  

I guess convert.py would seamlessly work if it goes through the same IO class.  

— Gábor

**Comment by jameskermode** [comment]
For uncompressed tar files appending is efficient. If we want compression this won't work as it's the entire .tar file which is compressed, not the members of the archive. So to append you have to decompress, add the frame and recompress.

**Comment by gabor1** [comment]
ok. so it would be good to have the IO class work automatically with both compressed and uncompressed versions. there is still the minor inconvenience of having to extract a configuration if you want to look at it on the command line. do you envisage retaining the concatenated xyz format (and so just ditching the .idx system? )

— Gábor

**Comment by cortner** [comment]
Probably to get started, just having large xyz files will be easiest, but

> How about storing xyz frames in a (gzipped) tarball, so the index lives with the data? This would allow efficient random access, and could then still inspect with standard tools.

I like that, for an extension in the near future?

**Comment by jameskermode** [comment]
I think we're converging on:

- Retaining concatenated .xyz as basic fileformat for JuLIP
- Dropping .xyz.idx
- In future: tarball frame sequence, with provision for command line access

I'll have a go at a native Julia implementation of the extended XYZ routines at some point: I suspect they can be made much faster than the pure Python version in `ase.io.extxyz`, but for now let's just call ASE.

**Comment by cortner** [comment]
should this work:
```python
In [7]: fh = open("tmp.xyz", "w")

In [9]: import ase.build

In [10]: at = ase.build.bulk("Cu")

In [11]: import ase.io

In [12]: ase.io.write(fh, at)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-12-5696be10fd57> in <module>()
----> 1 ase.io.write(fh, at)

/Users/ortner/.local/lib/python2.7/site-packages/ase/io/formats.pyc in write(filename, images, format, **kwargs)
    257         if fd is not None:
    258             raise ValueError("Can't write {0}-format to file-descriptor"
--> 259                              .format(format))
    260         io.write(filename, images, **kwargs)
    261

ValueError: Can't write json-format to file-descriptor

In [13]: fh
Out[13]: <open file 'tmp.xyz', mode 'w' at 0x1087e6930>
```

**Comment by jameskermode** [comment]
Oops - when the filename is not there it can't infer the format, so this must be specified:

```
ase.io.write(fh, at, format='xyz')
```

**Comment by cortner** [comment]
works great - thank you.

**Comment by cortner** [comment]
should have said:  storing multiple configurations in one file should work ok now; see `JuLIP.ASE.write` (with `mode=:append` or `mode="a"). I'll try to to the `position_dofs` and `momentum_dofs` next and implement a Newtonian dynamics example.

**Comment by cortner** [comment]
right; I guess this can now also be close; cf #39
