### ISSUE TITLE
PyAMG

### ISSUE THREAD

**Issue by git4lei** [libAtoms/JuLIP.jl#34]
Hi Christoph,

When I try testsolve.jl (with include("testsolve.jl"), I got the following error message,

---
## same test but large and with Exp preconditioner

ERROR: LoadError: MethodError: no method matching PyAMG.AMGSolver{PyAMG.RugeStuben}(::SparseMatrixCSC{Float64,Int64}; tol=1.0e-7)

I tried to use "using PyAMG" first also with include("runtests.jl"), but those gave me the same error.

Best regards,
Lei

**Comment by cortner** [comment]
Can you  
```
Pkg.checkout("PyAMG")
```
and then try again?

**Comment by git4lei** [comment]
The error remains the same.

Lei

**Comment by cortner** [comment]
Does this only happen for the tests, or does it also happen when you just try to run the notebook we wrote? I.e. when you `minimise!` with preconditioner?

**Comment by git4lei** [comment]
It only happens for the tests. It works fine for the notebook we wrote.

Lei

**Comment by cortner** [comment]
then for now maybe turn off `testsolve.jl` and when you are back at Warwick I'll have a look.

**Comment by cortner** [comment]
has this ever been resolved?

**Comment by git4lei** [comment]
Yes, this has been resolved now, thanks.
