### ISSUE TITLE
Enable automatic installation of Python dependencies

### ISSUE THREAD

**Issue by jameskermode** [libAtoms/JuLIP.jl#38]
The following seems to work for the Travis-CI tests, but may not be optimal

```julia
ENV["PYTHON"]=""
Pkg.add("PyCall")
Pkg.add("Conda")
using Conda
Conda.add("NumPy")
Conda.add("SciPy")
Conda.add("pip")
pip = joinpath(Conda.BINDIR, "pip")
run(`$pip install ase`)
run(`$pip install -e git+https://github.com/libAtoms/matscipy#egg=matscipy`)
Pkg.clone(pwd())
Pkg.build("JuLIP")
Pkg.test("JuLIP"; coverage=true)
```

**Comment by cortner** [comment]
would be great if `Pkg.build("JuLIP")` could be used to install all of this?

**Comment by jameskermode** [comment]
I think this just requires putting the above into a `deps/build.jl` script? I haven't quite understood how this interoperates with `REQUIRE` so I might leave it to you so I don't break everything.

**Comment by cortner** [comment]
I've never done it but I should learn. I'll have a look.

**Comment by jameskermode** [comment]
@cortner we should revisit this. matscipy has now been released on PyPI so `pip install matscipy` should work reasonably easily cross platform. This means I no longer propose to port the neighbour list inside JuLIP - I think it's better to keep separate to keep up with bug fixes etc and avoid code duplication.

**Comment by cortner** [comment]
agree to keep the neighbour list in `matscipy`. However, maybe we could then produce  plain-C interface that doesn't require going via Python?

**Comment by cortner** [comment]
I just modified the build script to account for the easier installation of matscipy

**Comment by cortner** [comment]
after we test this, we can probably close this issue?

**Comment by gabor1** [comment]
I forsee someone at some point in the future wanting a pure-julia version … I am encountering difficulties intstalling matscipy for windows (for educational purposes - most students come with )…   not saying this to change anyone’s course of action right at this point, just mumbling. 

-- Gábor

**Comment by cortner** [comment]
I agree - see #63

**Comment by cortner** [comment]
in fact if it is mostly for educational purposes, then something not too fast would be ok? there is still #1  - it works great for clusters. Just need to test how well it works with PBCs.

**Comment by jameskermode** [comment]
I agree in principle, but think the time when one can use Julia for materials modelling without a working Python and `pip` installation is some way away.

@cortner the low-level neighbour_list C call looks like this:

```python
_matscipy.neighbour_list(quantities, a.cell,
                                    np.linalg.inv(a.cell.T), a.pbc,
                                    a.positions, cutoff, *args)
```

so it can already be called without an ASE Atoms object, but doing it without Python at all is much harder, as the Python API is very convenient for building up variable length return arrays etc.

**Comment by gabor1** [comment]
ah!

but here is the rub. getting python working on windows is no problem, Anaconda is fine. it’s the c compiler that’s the problem (and the problem keeps running away from solutions, with every minor python version!).

and yes, speed is sorta important, that’s why pure python doesn’t work very well. 

-- Gábor

**Comment by jameskermode** [comment]
Oops, probably premature to close as I see more commits But the new build.jl is working for me.

**Comment by cortner** [comment]
> and yes, speed is sorta important, that’s why pure python doesn’t work very well. 

For clusters, the `NearestNeighbours` package is faster than James' list :). but I suspect it won't do as well with PBC, because the result needs to be post processed to get the periodic images. But probably we are talking about a small factor. So still *much* more performant than any pure python.

**Comment by cortner** [comment]
ok, I'll close this once travis confirms everything is ok. And I'll move anything relevant to a separate issue.

**Comment by cortner** [comment]
there currently seem to be multiple bugs on Julia/Anaconda/Travis for OSX right now, which is why the tests fail.  but the automatic installation seems to work ok on travis, for both Linux and OSX, so I am closing this. We can re-open if needed.
