### ISSUE TITLE
Very Short Codes

### ISSUE THREAD

**Issue by cortner** [libAtoms/JuLIP.jl#46]
S Johnson pointed out that EAM can simply be written as `f2(sum(f1, r))`. What else can be made this short?

**Comment by gabor1** [comment]
Fine for understanding, but hard to parallelize in this way, and harder to make cheap single atom moves.  

-- Gábor

**Comment by cortner** [comment]
Actually in v0.6 and beyond there are plans that such constructions are automatically parallelised across threads.

**Comment by gabor1** [comment]
Threads is easy, I meant data parallelism. Other than that, This is indeed the standard formula for EAM.

-- Gábor

**Comment by cortner** [comment]
will take care of some of these optimisations during move to v0.6, but no really important so I am closing this
