### ISSUE TITLE
NaN energy when calling Atomistica potentials via ASE

### ISSUE THREAD

**Issue by jameskermode** [libAtoms/JuLIP.jl#48]
The following script demonstrates the error. We tracked it down as far as `set_position_dofs!()`.

[atoms_broken_relaxed.xyz.txt](https://github.com/libAtoms/JuLIP.jl/files/780896/atoms_broken_relaxed.xyz.txt)

```julia
using PyCall
using JuLIP
@pyimport atomistica
@pyimport ase

atoms = ASEAtoms(ASE.ase_io.read("atoms_broken_relaxed.xyz"))
calc = ASECalculator(atomistica.TersoffScr())
set_calculator!(atoms, calc)

set_constraint!(atoms, FixedCell(atoms))
println(energy(atoms))
println(energy(atoms, dofs(atoms)))
```

Results are:

```
julia> include("run.jl")
-2040.7844479506173
NaN
```

i.e. second call to `energy(atoms, dofs(atoms))` gives a NaN result.

**Comment by jameskermode** [comment]
Here's a slightly simpler but equivalent example:

```julia
using PyCall
using JuLIP
@pyimport atomistica
@pyimport ase

atoms = ASEAtoms(ASE.ase_io.read("atoms_broken_relaxed.xyz"))
calc = ASECalculator(atomistica.TersoffScr())
set_calculator!(atoms, calc)
set_constraint!(atoms, FixedCell(atoms))

println(energy(atoms))
set_positions!(atoms, positions(atoms))
println(energy(atoms))
```

**Comment by jameskermode** [comment]
Changing the definition of `positions(at::ASEAtoms)` from
```julia
positions(at::ASEAtoms) = copy( pyarrayref(at.po["positions"]) ) |> vecs
```
to
```julia
positions(at::ASEAtoms) = at.po[:get_positions]()' |> vecs
```
appears to solve this problem. I don't fully understand why, but since a copy is made in either case, avoiding the `unsafe_wrap()` is probably good. If there are no objections I will check this in after a bit more testing.

**Comment by cortner** [comment]
The fix makes 2 copies. Ok to make sure t works but we should find the bug.

**Comment by jameskermode** [comment]
Yes, I just realised that. I'll try with `PyReverseDim()`.

**Comment by jameskermode** [comment]
I'm homing in on the problem. If `a = PyArray(atoms.po["positions"])`, then `unsafe_wrap(Array, a.data, reverse(a.dims))` (what we use now) does not give array elements in the same order as `transpose(unsafe_wrap(Array, a.data, a.dims))` (what we want) since the Python array is in C (row-major) order. I don't have a solution that doesn't involve a copy yet.

**Comment by jameskermode** [comment]
The plot thickens... I finally understand why this happens when reading from an .xyz file but not when creating structures with `bulk()`. In the former case the numpy `positions` array is Fortran-contiguous, in the latter it's C-contiguous. Perhaps a bug in the ASE xyz reader (it's me that wrote that).

**Comment by cortner** [comment]
very interesting.

**Comment by cortner** [comment]
There is [this issue](https://github.com/JuliaLang/julia/pull/20047), which discusses a `TransposeMatrix` type, but I don't think it is implemented yet. But once it exists we can simply check what the storage type of the Python array is and import the `unsafe_positions` either as `Matrix` or as `TransposeMatrix`. Until then, maybe we need to drop `unsafe_positions` or make the behaviour undefined (as make it undefined whether one gets a reference or a copy).

**Comment by jameskermode** [comment]
I think it's just a bug in the ASE XYZ reader: I assemble the columns using `vstack()` which leads to Fortran memory ordering. I've created a [pull request](https://gitlab.com/ase/ase/merge_requests/424) with a fix, once the ASE guys merge this then we can revert commit  66bcf2eb and close this issue.

**Comment by cortner** [comment]
thats fine for me if there is a guarantee that ASE will *always* use the memory layout we assume now? It just never occurred to before that it might not, but now I am worried.

**Comment by jameskermode** [comment]
I think it should always be in C order, but the problem is that from Python you often don't notice if the memory is in C or Fortran order since numpy abstracts it completely, unless you look very carefully (or notice slow downs).

**Comment by jameskermode** [comment]
If we are worried we could actually check the flags of the numpy array before doing the `unsafe_wrap`. I'll have a go at this.

**Comment by cortner** [comment]
this is my point - can we *guarantee* that ASE will always have positions stored in C order? If not then we need to check before we import them into JuLIP.

**Comment by cortner** [comment]
right, that's what I meant. And maybe for the time being, if positions are stored in F order then let `unsafe_` thing just return a copy instead of a reference?

**Comment by jameskermode** [comment]
Probably `unsafe_positions` should raise an error rather than returning a copy, otherwise you might be expecting to be able to modify in place. But `positions()` should be made to return a copy in correct memory layout.

**Comment by cortner** [comment]
Ok then let's raise an error for now and switch it to TransposeMatrix once it exists.

C

Sent from my iPhone

On 16 Feb 2017, at 21:16, James Kermode <notifications@github.com<mailto:notifications@github.com>> wrote:


Probably unsafe_positions should raise an error rather than returning a copy, otherwise you might be expecting to be able to modify in place. But positions() should be made to return a copy in correct memory layout.

**Comment by cortner** [comment]
I guess this will be fixed once we create a pure Julia Atoms.
