### ISSUE TITLE
Array Conversions Python to/from Julia

### ISSUE THREAD

**Issue by cortner** [libAtoms/JuLIP.jl#5]
It looks as if, at the moment, we make two copies of a positions (or similar) array when converting between ASE and JuLIP. First copying from Julia to Python and then transposing; but the memory layout of the original and final are the same, so it should be possible to convert between the JuLIP and ASE arrays and never copy them.

**Comment by jameskermode** [comment]
I manage this between Fortran and Python with quippy by creating memory-mapped arrays that point to the same underlying data. Numpy has an `ndarray.view` method that can reshape and/or transpose without creating a copy.

**Comment by cortner** [comment]
I believe `PyCall` has a way to do this, I just haven't found the time to look at the documentation.

**Comment by cortner** [comment]
Just taking notes on what I've found so far: 
```
Xpy = PyArray(at.po["positions"])
X = unsafe_wrap(Array, Xpy.data, reverse(Xpy.dims), false)
```
creates a Julia array `X` which accesses the same memory as `at.positions` (in Python)

The main risk seems to be that, if `positions` is freed in Python, then Julia won't know this. Julia can take ownership by sending the argument `own=true` instead of `false`, but then the memory might be freed accidentally while Python still wants to access it.
