### ISSUE TITLE
Computing distance of two configurations when one of the two jumps across the PBC.

### ISSUE THREAD

**Issue by SMakri** [libAtoms/JuLIP.jl#50]
> The aim is to define a distance between images along the string at the net of “jumps" across the PBC as it evolves.

> So, the issue is that I have two configurations X1, X2, and I want to compute the difference X2 - X1 but need to do it in a continuous way.

> One atom of X1 may cross the unit cell boundary during dynamics/relaxation without the same atom crossing in X2.

_computing min configuration distance:_
```python
def undo_pbc_jumps(at):
    if not at.has('prev_pos'):
        at.set_array('prev_pos', at.get_positions())
    prev_pos = at.get_array('prev_pos')
    p = at.get_positions().T
    g = np.linalg.inv(at.get_cell().T)
    p -= np.dot(at.cell.T, np.floor(np.dot(g, (p - prev_pos.T))+0.5))        
    at.positions[:] = p.T
    at.set_array('prev_pos', p.T)
 
def pbc_diff(a, b):
    aa = a.copy()
    undo_pbc_jumps(aa)
    bb = aa.copy()
    bb.set_positions(b.positions)
    undo_pbc_jumps(bb)
    return aa.get_positions() - bb.get_positions()
```

**Comment by cortner** [comment]
CC @SMakri  @jameskermode 

before I implement this, I'd like to know how it will be used. Is the use-case that I have an atoms object `at` and two position arrays `X1, X2`  (both valid for this `at`) and I then want to call, 
say, 
```
  dist(at, X1, X2, p) = dist(cell(at), X1, X2, p)
```

**Comment by jameskermode** [comment]
Yes, that's right - or equivalently two atoms objects `dist(at1, at2)`.

By the way, what is `p` above?

**Comment by cortner** [comment]
p-norm.

so in the `dist(at1, at2)` variant we are implicitly assuming that position indices match? we don't first create some sort of minimal distance permutation?

**Comment by jameskermode** [comment]
Yes - if the documentation string makes clear the configurations should be isoatomic then there's no need to permute.

The use case is comparing distinct images from the same NEB or string, when we know they are ordered the same, but something might jump over a periodic boundary.

**Comment by cortner** [comment]
implemented with commit b0e88a1ce683dc38c089bccb07496dcb76536071. I implemented a basic test, which seems to pass ok, but if there are any issues just reopen this or open a new issue please

**Comment by cortner** [comment]
P.S.: see 
```
using JuLIP
?dist
```
for the documentation.

**Comment by jameskermode** [comment]
We might need to re-open this, as @SMakri need's pbc-corrected displacement vectors, not just distances. We can discuss tomorrow.

**Comment by gabor1** [comment]
lots of people use pbc corrected displacement vectors! 

-- Gábor

**Comment by cortner** [comment]
Is this the definition:

If x -> x' = x + u, then the PBC corrected u is the shortest periodic image of u?

**Comment by gabor1** [comment]
That's one use. Another thing that quippy used to do is to keep track of the pbc wraparounds, so that you could compute "real" displacements, ie as if you were running a very big ("pbc replicated ") system, thus unfolding all the pbc wraps. Useful for diffusion calculations

-- Gábor

**Comment by jameskermode** [comment]
You have coded `dist(at1, at2)`, but we also need `diff(at1, at2)` or `diff(at, positions2)`, `diff(at, positions1, positions2)`

**Comment by cortner** [comment]
I guess I dropped the ball on this - sorry, I'll make it a priority.

**Comment by cortner** [comment]
Just pushed something to `master` that should contain this functionality:
```
at = bulk("Si", cubic=true) * 2
cell(at)
X1 = positions(at)
X2 = copy(X1)
X2[1] = JVecF(-9.234, 0.1, -1.234)
displacement(at, X1, X2)
```
@SMakri are you willing to test this?
