### ISSUE TITLE
LennardJones energy ~zero for dimer for all bondlengths

### ISSUE THREAD

**Issue by jameskermode** [libAtoms/JuLIP.jl#57]
Am I doing something obviously stupid here? I'm trying to plot the dimer energy curve for `LennardJones` but get ~zero for all bond lengths. Same code works OK with `StillingerWeber` (after adjusting linspace range).

```julia

using JuLIP
using JuLIP.Potentials

si = ASEAtoms("Si2")
set_cell!(si, 100.0*eye(3))
set_pbc!(si, true)

p = positions(si) |> mat
sw = LennardJones(1.0, 1.0)
#sw = StillingerWeber()
set_calculator!(si, sw)
forces(si)

r = linspace(0.5, 1.5, 10)
e = []
for d in r
    p[1,1] = d
    set_positions!(si, p)
    push!(e, energy(si))
end
(r, e)
```

Output:
```
(linspace(0.5,1.5,10),Any[-3.02097e-69,-3.02097e-69,-3.02097e-69,-3.02097e-69,-3.02097e-69,-3.02097e-69,-3.02097e-69,-3.02097e-69,-3.02097e-69,-3.02097e-69])
```

**Comment by cortner** [comment]
Hi James,

This is a bug in the neighbourlist. lj = LennardJones() has cutoff(lj) = Inf. And apparently the matscipy neighourlist doens’t like that and results in an empty list. Funny that I never checked that. The obvious solution is to replace 

sw = LennardJones() 

with 

sw = LennardJones(1.0, 1.0) * SplineCutoff(10.0, 20.0)

then you’ll barely notice the difference and it now has a cutoff of 20, and everything is happy. 

Just to check: are you sure you want pbc = true?

Christoph

**Comment by cortner** [comment]
This is a bug in the neighbourlist. `LennardJones()` has infinite cutoff and the matscipy neighbourlist is apparently not prepared for that and returns an empty list. Funny that I never checked that case.

The obvious solution is to replace 
```
sw = LennardJones()
```
with 
```
sw = LennardJones() * SplineCutoff(10.0, 20.0)
```
then you'll barely notice the cut-off and the neighoburlist is happy.

Just to check: are you sure you want `pbc=true`?

**Comment by jameskermode** [comment]
Perfect, got it, thanks. Yes, `pbc=true` is what I meant, odd though it seems.
