### ISSUE TITLE
Add read() function that calls ase.io.read

### ISSUE THREAD

**Issue by jameskermode** [libAtoms/JuLIP.jl#62]
Could be as simple as this:

```julia
import JuLIP.ASE

function read(filename)
    atoms = JuLIP.ASE.ase_io.read(filename)
    return JuLIP.ASE.ASEAtoms(atoms)
end
```

But perhaps name shouldn't clash with builtin `read()`?

**Comment by cortner** [comment]
I've now imported `Base.write` and `Base.read`. I see no reason to not overload.

this is implemented as of d0a85c65dff49a62bdb101f65ae30b53d6902dc1
