### ISSUE TITLE
Pure Julia `Atoms`

### ISSUE THREAD

**Issue by cortner** [libAtoms/JuLIP.jl#63]
CC @jameskermode 

I thought, we'd collect some ideas and action points to discuss how to and the consequences of a pure Julia `Atoms` object. 

### TODO
* [x] pure Julia neighbourlist (EDIT)

**Comment by cortner** [comment]
Q1: store positions, momenta as fields, or in a dictionary Dict{Any, Vector{JVecF}} for storing only arrays of 3-vectors, so they can be extracted without type instability.

**Comment by cortner** [comment]
Storing the cell as a matrix creates ambiguities. Are the columns or the rows the cell vectors? I would like to switch storing the cell as a list of vectors,
```
# either 
Tuple{JVec, JVec, JVec}
# or 
Vector{JVec}
```

**Comment by cortner** [comment]
I won't do this, to keep compatibility with ASE. But instead introduced `cell_vecs` to get the vectors instead of the matrix.

**Comment by gabor1** [comment]
can I plead for full words as names.. cell_vectors is just fine!

-- Gábor

**Comment by jameskermode** [comment]
Normally I would agree, but the function that goes from matrix to vector is already called `vecs()`

**Comment by cortner** [comment]
> Normally I would agree, but the function that goes from matrix to vector is already called vecs() 

that was the reason, but I'll think about it.

**Comment by gabor1** [comment]
That's fine then.

Vecs breaks up the matrix into a bunch of vectors?

-- Gábor

**Comment by cortner** [comment]
C^T = [ c1 c2 c3 ]

where ci are of type SVector{T}
