### ISSUE TITLE
StepFunction

### ISSUE THREAD

**Issue by cortner** [libAtoms/JuLIP.jl#65]
CC @jameskermode 

```
using JuLIP, JuLIP.Potentials, PyPlot
V = PairPotential(:( (r-1.0)^2 - 1.0 )) * StepFunction(2.0)
r = linspace(0, 3, 101)
plot(r, V.(r), "b-")
axis([0, 3, -1.1, 1.1])
```

<img width="564" alt="screen shot 2017-06-01 at 22 12 57" src="https://cloud.githubusercontent.com/assets/7688515/26701069/a22894f4-4717-11e7-8de4-5b869f913fa0.png">

**Comment by cortner** [comment]
see ff67931866338390b408c55b285d5687703a3fd8

**Comment by jameskermode** [comment]
Thanks, this is perfect!
