### ISSUE TITLE
Matscipy Neighbourlist

### ISSUE THREAD

**Issue by cortner** [libAtoms/JuLIP.jl#66]
@jameskermode wrote in another issue: 

@cortner the low-level neighbour_list C call looks like this:

```python
_matscipy.neighbour_list(quantities, a.cell,
                                    np.linalg.inv(a.cell.T), a.pbc,
                                    a.positions, cutoff, *args)
```

so it can already be called without an ASE Atoms object, but doing it without Python at all is much harder, as the Python API is very convenient for building up variable length return arrays etc.

**Comment by cortner** [comment]
So the advantage of this would be that I don't need the `ase.Atoms` object anymore, but I still have the problem that I need to either copy all the arrays again, or run into the same issues with referencing that I have now. Who knows though, maybe those issues arise from what ASE does with the arrays, so by going around ASE I might be in a better position. I'll play with this when I have time.

**Comment by jameskermode** [comment]
The referencing issues in #48 come from the ability for numpy arrays to be either C- or contiguous, so by avoiding `ase.Atoms` and creating arrays yourself from Julia you should be able to avoid this.

However, in general I think the interoperability gain of being able to easily call ASE calculators to drop in new potentials and codes is likely to outway any performance hits of copying arrays.

**Comment by cortner** [comment]
I don't mean to get rid of ASE, just want to resolve some robustness issues I ran into a few times.

**Comment by cortner** [comment]
do you happen to know the return values off the top of your head? no worries if not, I will find out.

**Comment by jameskermode** [comment]
Same as https://github.com/libAtoms/matscipy/blob/master/matscipy/neighbours.py#L62 so it depends what you ask for in `quantities` - if you pass `ijd` then the C-function returns a 3-tuple of arrays `(i, j, d)`

**Comment by jameskermode** [comment]
@pastewka has written a pure Python implementation of the matscipy neighbour list. Once this has been merged into ASE we could drop JuLIP's dependency on matscipy (although it's a bit slower than the C code; the new pure Python version could also serve as a template for porting to Julia is someone is feeling keen).

https://gitlab.com/ase/ase/merge_requests/763/

**Comment by cortner** [comment]
That might be good, though we should still port it or write a new one based on NearestNeighbours.jl

**Comment by pastewka** [comment]
You may be able to do something more clever in Julia than I did in Python. Neighbor list search is something that does not very well map onto vectorized expressions...

**Comment by cortner** [comment]
pure Julia implementation of matscipy neighbour list is now in NeighbourLists.jl
