### ISSUE TITLE
incorrect override of show/display

### ISSUE THREAD

**Issue by stevengj** [libAtoms/JuLIP.jl#67]
You are overriding `show(x)` to call `display(x)`, which isn't how these functions are intended to be customized.  See the manual on [custom pretty printing](https://docs.julialang.org/en/release-0.6/manual/types/#Custom-pretty-printing-1).

To customize REPL output, you should override `Base.show(io::IO, x::MyType)` and/or `Base.show(io::IO, ::MIME"text/plain", x::MyType)`, as explained in the manual.

**Comment by cortner** [comment]
I assume you are referring to 
```
show(at::AbstractAtoms; kwargs...) = display(at; kwargs...)
```
this really should have been a deprecation of `show` which I had incorrectly used in the past and wanted to switch it to `display` but not break some codes. I've now removed this on master though.

There were also some other incorrect usage cases of `print` where `show` should be used, which I've also fixed now. 

Thank you for pointing this out.

**Comment by cortner** [comment]
P.S.: the `display(at::AbstractAtoms; kwargs...) ` function does not print to the REPL but creates a 3D visualisation.

**Comment by stevengj** [comment]
@cortner, you normally shouldn't be overriding `Base.display` for that.  e.g. this will break on something like JuliaBox.

**Comment by cortner** [comment]
what should I be using?  (I didn't find the Multimedia IO documentation very informative)

I am also curious: how did you run into this package and what is your interest in fixing this issue?

So far the number of users is so small that I never worried about issues like this. I never tried it on Juliabox. But I'll be very happy to try and conform better with how IO is intended.

**Comment by cortner** [comment]
I decided to rename `JuLIP.Visualise.display`  -> `draw` (already on master); that seems to fit better anyhow and gives me the option to use `display` to override text output.  

Let me know if you have other concerns.

**Comment by stevengj** [comment]
I help maintain IJulia, and keep running into packages that incorrectly override `display`, so I did a search for all registered packages that override `Base.display`.

**Comment by stevengj** [comment]
(Note that you *don't* override `display` to override text output.  See the link in the top post above.)

**Comment by gabor1** [comment]
hi Steven!  

thanks for sorting us out.  

(and thanks for Julia too!)

-- Gábor

**Comment by cortner** [comment]
Thanks again - any other concerns or can I close this?

**Comment by stevengj** [comment]
LGTM
