### ISSUE TITLE
Transition to Julia 0.6

### ISSUE THREAD

**Issue by cortner** [libAtoms/JuLIP.jl#68]
I am thinking of slowly start transitioning to Julia v0.6 in preparation for v0.7 = v1.0. Apparently jumping a version is not advised. Any concerns?

**Comment by jameskermode** [comment]
Fine for me. I'm already using 0.6 in some places and JuLIP mostly works OK, with deprecating warnings for the missing broadcast operations (e.g. `sqrt.(vec)` not `sqrt(vec)`).

**Comment by cortner** [comment]
my inclination then would be to develop the 0.6 version as the master branch but keep a separate branch for v0.5 that gets at most bug-fixes.

**Comment by gabor1** [comment]
yeah, I’m mostly on 0.6 as well

-- Gábor

**Comment by cortner** [comment]
transition going well so far, I am just listing the remaining issues here:
*[ ] `P.p = update_inner!(P.p, at)` in `force_update!(P::DirectPrecon, at::AbstractAtoms)` redefines a method which apparently crashes the matrix assembly in v0.6 and most likely was a bug in v0.5. Why was this even needed?

**Comment by cortner** [comment]
all tests passing, only issue left (as can be seen from the tests) is the item above.

**Comment by cortner** [comment]
this is now registered, `Pkg.add("JuLIP")` will now install the latest version on v0.6. I am filing a separate issue for the workaround I used in the preconditioner matrix assembly
