### ISSUE TITLE
Redefining Methods and World Age

### ISSUE THREAD

**Issue by cortner** [libAtoms/JuLIP.jl#69]
There is an interesting new "feature" in v0.6 : "In version 0.6, Julia now keeps track of all the callers of a given function (called backedges) so it can go back and invalidate the previous code with any updated methods."

See e.g. 
* https://discourse.julialang.org/t/running-in-world-age-x-while-current-world-is-y-errors/5871
* https://discourse.julialang.org/t/applicable-method-may-be-too-new-error/2733
* https://discourse.julialang.org/t/help-with-solving-a-world-age-error-in-package-on-julia-master/1126

The is explained in detail in [Redefining Methods](https://docs.julialang.org/en/stable/manual/methods/#Redefining-Methods-1)

Related from #68 : 
preconditioner matrix assembly in v0.6 crashes; cf. preconditioners.jl / testsolve.jl; I am now guessing that the problem has something to do with either the precomputation of the refactor and then redifinition; or with the @D, @DD macros. Will need to revisit them or get rid of them. Or quite possible there is a problem with the way the analytic potentials are defined. . .

**Comment by cortner** [comment]
MWE: 
```.jl
inner(f) = f(rand())

function test()
   f = eval( :( r -> exp(-r) ) )
   inner(f)
end

test()
```

**Comment by cortner** [comment]
It turns out this is actually a huge problem. A file containing the following script works:
```julia
using JuLIP, JuLIP.ASE, JuLIP.Potentials
calc = lennardjones(r0=JuLIP.ASE.rnn("Al"))
at = bulk("Al", cubic=true) * (20,20,2)
set_calculator!(at, calc)
set_constraint!(at, FixedCell(at))
gradient(at)
```
but the next one generates an error
```julia
using JuLIP, JuLIP.ASE, JuLIP.Potentials
function test()
   calc = lennardjones(r0=JuLIP.ASE.rnn("Al"))
   at = bulk("Al", cubic=true) * (20,20,2)
   set_calculator!(at, calc)
   set_constraint!(at, FixedCell(at))
   gradient(at)
end
test()
```

**Comment by cortner** [comment]
A temporary fix would be to wrap all functions generated with `eval` using `FunctionWrappers`, this comes with a ca 10% performance penalty

**Comment by cortner** [comment]
posted at [discourse](https://discourse.julialang.org/t/how-to-bypass-the-world-age-problem/7012)

**Comment by cortner** [comment]
solution due to @ettersi:
```julia
using Calculus: differentiate
function Base.diff(ex::Expr)
   ex_d = differentiate(ex, :r)
   return eval( :( (r->$ex, r->$ex_d)) )
end
type AnalyticPotential{F0,F1}
   f::F0
   f_d::F1
end
macro AnalyticPotential(expr)
   :(
      AnalyticPotential(
          r->$expr,
          r->$(differentiate(expr,:r))
      )
   )
end
inner(p) = p.f(rand())
function test()
   # p = AnalyticPotential( diff(:( exp(-r) ))... )
   p = @AnalyticPotential exp(-r) 
   inner(p)
end
test()
```

**Comment by cortner** [comment]
Unfortunately, this won't work: 
```
a = 1.0 
p = @AnalyticPotential exp(a*r)
@show p.f(1.0)  # 2.718281828459045
a = 2.0 
@show p.f(1.0)  # 7.38905609893065
```

**Comment by cortner** [comment]
Here are the timings for Wrapped vs unwrapped potentials:
```
Timing Lennard-Jones:
  0.016561 seconds (19 allocations: 75.578 KiB)
  0.017770 seconds (19 allocations: 75.578 KiB)
  0.016917 seconds (19 allocations: 75.578 KiB)
Timing Lennard-Jones-Wrapped:
  0.021734 seconds (19 allocations: 75.578 KiB)
  0.023149 seconds (19 allocations: 75.578 KiB)
  0.024302 seconds (19 allocations: 75.578 KiB)
Timing Stillinger-Weber:
  0.007784 seconds (121.62 k allocations: 7.178 MiB)
  0.019893 seconds (121.62 k allocations: 7.179 MiB, 57.78% gc time)
  0.009960 seconds (121.62 k allocations: 7.178 MiB)
Timing Stillinger-Weber-Wrapped:
  0.017970 seconds (121.62 k allocations: 7.179 MiB, 36.49% gc time)
  0.011683 seconds (121.62 k allocations: 7.178 MiB)
  0.010559 seconds (121.62 k allocations: 7.178 MiB)
```

**Comment by cortner** [comment]
See also this [GIST](https://gist.github.com/cortner/0ba7884581ec921aa32fc9a5637cfa1c) for more benchmarking

**Comment by cortner** [comment]
There are two short-term options:
1. leave as is, but document the problem and explain that one needs to use wrapped potentials if the world age problem occurs. 
2. make wrapped potentials the default, which seems to come with a 20% to 30% performance penalty.

**Comment by cortner** [comment]
Workaround for the problem is to enforce dynamic dispatch at the call-site (rather than in the definition of the potential) using `invokelatest`; see new [benchmark gist](https://gist.github.com/cortner/0ba7884581ec921aa32fc9a5637cfa1c) and the [discussion](https://discourse.julialang.org/t/how-to-bypass-the-world-age-problem/7012/25)

**Comment by jameskermode** [comment]
This seems like a fairly serious regression. Do I understand correctly that it only causes problems in REPL/notebooks when potentials are redefined?

**Comment by jameskermode** [comment]
I now looked at your benchmark timings, it seems like the `invokelatest()` version has very little overhead so this fine?

**Comment by cortner** [comment]
I had just misunderstood `invokelatest`. It actually has huge overhead, so if I were to apply it inside a performance-critical loop then it would be awful. But in the latest timings I am effectively using a type inference barrier function, i.e., outer function is interpreted, but inner function is compiled. Without `invokelatest` this runs into this world age problem, while `invokelatest` enforces dynamic dispatch which doesn't have this problem to begin with. Is my explanation making sense?

**Comment by cortner** [comment]
Just had a very useful discussion with Simon (he is teaching me to write macros :)). His suggestion is to replace generating analytic potentials via `eval` with a macro. The usage would the be as follows: 
```julia
a, r0 = params()
# Old 
p = PairPotential( :(  exp( - $a * (r/$r0 - 1.0) ) ), :r )
# New 
p = @PairPotential r -> exp( - a * (r/r0 - 1.0) )
```
Apart from being more readable (I think) it completely circumvents the need for `invokelatest`.

**Comment by jameskermode** [comment]
I agree it's much more readable using `@PairPotential` form, especially the way it removes the need for expression quoting and `$r` etc. I don't think the updating of parameters is too bad either, providing one is aware of it. 

How does using macros interoperate with type inference? Can we still have a type hierarchy, with, e.g. a corresponding `PairPotential` type?

**Comment by cortner** [comment]
The macro @PairPotential will generate an object `p::PairPotential` where `PairPotential` is the same object as before. So the  type hierarchy would remain unchanged.

**Comment by jameskermode** [comment]
Great- I was worried there would be a clash between macro `@PairPotential` and type `PairPotential` but I guess this is fine. If it's not too much work to convert code to macro form I think this would be worthwhile.

**Comment by cortner** [comment]
if I really wanted to get ambitious then it would actually be possible to write a macro like this: 
```
a = 1.234; r0 = 0.9
p = @PairPotential r -> exp( - a * (r/r0 - 1.0) ),  let = a, r0
```
which would wrap this all into a `let` block so the user doesn't have to.

**Comment by cortner** [comment]
ok - then I'll get going on this (not the ambitious version though!)

**Comment by cortner** [comment]
thank you for the input!

**Comment by cortner** [comment]
for future reference, I've put all the different variants into the [gist](https://gist.github.com/cortner/0ba7884581ec921aa32fc9a5637cfa1c)

**Comment by cortner** [comment]
#70 should take care of everything in here (and more)
