### ISSUE TITLE
Install issue on Linux Mint Machine

### ISSUE THREAD

**Issue by gideonsimpson** [libAtoms/JuLIP.jl#77]
I installed Julia 0.6.1 and JuLIP on a linux machine (with Python 2.7), and I get the following error:

```
julia> using JuLIP
ERROR: LoadError: LoadError: UndefVarError: JuLIP not defined
Stacktrace:
 [1] include_from_node1(::String) at ./loading.jl:576
 [2] include(::String) at ./sysimg.jl:14
 [3] include_from_node1(::String) at ./loading.jl:576
 [4] eval(::Module, ::Any) at ./boot.jl:235
 [5] _require(::Symbol) at ./loading.jl:490
 [6] require(::Symbol) at ./loading.jl:405
while loading /home/gsimpson/.julia/v0.6/JuLIP/src/preconditioners.jl, in expression starting on line 14
while loading /home/gsimpson/.julia/v0.6/JuLIP/src/JuLIP.jl, in expression starting on line 56
```
The install process did not indicate there had been any error.

**Comment by cortner** [comment]
Same problem as before: I haven’t tagged the latest master yet. Can you please 'Pkg.checkout("JuLIP")' and try again?

**Comment by gideonsimpson** [comment]
Ok, but now it's got the missing PyAMG issue

**Comment by cortner** [comment]
For now can you install it manually as before? I haven’t got around to fixing the automated installation yet, sorry.

**Comment by gideonsimpson** [comment]
Yes, that works

**Comment by cortner** [comment]
Since this is essentially a duplizill close it as well
