### ISSUE TITLE
Another lammps comparison

### ISSUE THREAD

**Issue by gideonsimpson** [libAtoms/JuLIP.jl#78]
Following up on the previous experiment comparing lammps out to julip, it seemed that we had resolved issue of the configuration of the atoms, with the discrepancies coming from periodicity.  Now, I'm looking at the energies, and, again, finding a distinction (despite the positions basically being in agreement).  In the following two codes, I compute the energy of the same initial configuration, quench, and then compute the quenched energy, and take the difference to account for differences in the constants.  The results are quite different.   lammps finds an energy difference between initial and final configurations of -1.6420470181480626, while julip finds a difference of -22.98865825399517.  

The lammps code is:
```
boundary p p p
units lj
atom_style atomic
atom_modify map array sort 0 0.0
dimension 2

region box block 0 20 0 20 0 10 units box
create_box 1 box

create_atoms 1 single 10 10 0
create_atoms 1 single 11 10 0
create_atoms 1 single 10.5 10.866025403784 0
create_atoms 1 single 9.5 10.866025403784 0
create_atoms 1 single 9 10 0
create_atoms 1 single 9.5 9.1339745962156 0
create_atoms 1 single 10.5 9.1339745962156 0

mass 1 1.0
pair_style lj/cut 2.5
pair_coeff 1 1 1.0 1.0
pair_modify shift yes
neighbor 0.3 bin
neigh_modify delay 0 every 1 check yes

variable eng equal pe

fix 99 all enforce2d
run 0

print "Initial Energy: ${eng}"
write_dump all atom lj72d_init.out modify scale no

min_style cg
minimize 1.e-14 1.e-14 1000 1000
run 0
write_dump all atom lj72d_min.out modify scale no

print "Minimal Energy: ${eng}"
```

while the julip code is:
```
using JuLIP, JuLIP.ASE, JuLIP.Potentials

# set up a heptamer
r0 = 1.0
N = 6
phi = linspace(0., (N-1)* 2*pi/N, N)|>collect
x0 = 10 # position of center
y0 = 10
x = x0 + [0; r0 * cos.(phi)]
y = y0 + [0; r0 * sin.(phi)]
X = [x';y';  zeros(N+1)']|> vecs
at = Atoms("H$(length(X))", X)
set_cell!(at, diagm([20, 20, 10]))
set_pbc!(at, (true, true, true))
set_constraint!(at, FixedCell2D(at))

lj = LennardJones(r0=2.^(1./6.), e0=1.) * HS(2.5)
set_calculator!(at, lj);

kBT = 0.1
nsteps = 10^4
dt = 1.e-4

q0 = position_dofs(at)
Einit = energy(at)

minimise!(at, gtol = 1e-14, precond=:id)
q = position_dofs(at)
Emin = energy(at)

println("Initial Positions")
display(reshape(q0,(2,7))')
println()
println("Initial Energy = $(Einit)")

println("Minimal Positions")
display(reshape(q, (2,7))')
println()
println("Energy after quench = $(Emin)")
println("Energy difference = $(Emin - Einit)")
```

**Comment by cortner** [comment]
not sure what is happening here, but let's just make a very rough estimate:

V(r) = 4* (r^(-12) - r^(-6))

Then if nn-dist is rnn = 2^(1/6) and V(rnn) = -1. Each atom has 3 neighbours except for the centre atom which has 6 neighbours gives total of 24 neighbours, so the total energy after relaxation should be roughly - 24. JuLIP gives -24.38442360766189, which due to the second neighbours and the shift. Sound to me like JuLIP is about right.

**Comment by cortner** [comment]
Further, I suggest that you use 
```
lj = (@analytic r -> 4*((1/r)^12 - (1/r)^6)) * C0Shift(2.5)
```
That way (1) you can control the precise functional form and (2) you use the correct energy-shift. `HS` is just the Heaviside function, you want to use `C0Shift, C1Shift, C2Shift`.

**Comment by cortner** [comment]
Ok, here is the reason you get this result: after changing the LJ potential to 
```
lj = (@analytic r -> 4*((1/r)^12 - (1/r)^6)) * C0Shift(2.5)
```
you get 
```
Energy difference = -11.494329126997563
```
and 
```
-11.494329126997563 / 7 = -1.642047018142509
```
