### ISSUE TITLE
EMT no longer consistent with ASE

### ISSUE THREAD

**Issue by cortner** [libAtoms/JuLIP.jl#81]
EMT used to be consistent with the ASE implementation to within machine precision, now the error is O(1e-5). Most likely this due to a change in ASE rather than a change in JuLIP, but need to test this.

**Comment by gabor1** [comment]
That sounds like some shifting protocol issue

-- Gábor

**Comment by jameskermode** [comment]
Or a change in fundamental constants used for unit conversion.

**Comment by cortner** [comment]
found the bug, fixed in  56d724453ab4a4cfaef9b256ecfe0b0af7ccd89c 

possibly I introduced it when transitioning to v0.6, which required a few changes to the infrastructure, or possibly ASE fixed a bug?
