### ISSUE TITLE
PyAMG dependency

### ISSUE THREAD

**Issue by thudso** [libAtoms/JuLIP.jl#88]
With a fresh JuLIP install, package testing fails because PyAMG dependencies are not fulfilled.

**Comment by cortner** [comment]
Thank you - which Julia version? For a quick fix: just use Pkg.add

**Comment by thudso** [comment]
Julia 0.6.2: manual fix works fine, thanks!

On 7 Feb 2018, at 22:31, Christoph Ortner <notifications@github.com<mailto:notifications@github.com>> wrote:


Thank you - which Julia version? For a quick fix: just use Pkg.add

**Comment by cortner** [comment]
For now, I've turned off `PyAMG`, and this is becoming irrelevant as `AMG.jl` is now available. Due to bugs (that only seem to occur for me) I haven't yet made it the default though.
