### ISSUE TITLE
Bug in constraints FixedCell()? - Nope

### ISSUE THREAD

**Issue by lifelemons** [libAtoms/JuLIP.jl#90]
Hey,

So I'm not sure if this is a bug or just my lack of understanding on how constraints work. I am also only using `FixedCell()` at the moment, so could be limited to this.

So creating a constraint inside and outside a function are not consistent, ie parts are not `==` to each other.
- `constraint` objects are the same when passed in as a variable
- `constraint` objects are different when generated inside a function
- `ifree` fields are the same for both base

It is not limited to the `free` keyword, the same results show for `mask` and `clamp` keywords.

The script below demonstrates this.

```
using JuLIP: Atoms, FixedCell

atoms = Atoms("Si2")
ifree = [1]
constraints_f = FixedCell(atoms, free=ifree)

function test(atoms, ifree, constraints_f)
    
    atoms_2 = Atoms("Si2") # atoms
    ifree_2 = [1] # ifree
    constraints_f_2 = FixedCell(atoms_2, free=ifree_2)
    constraints_f_cp = constraints_f
    
    return atoms_2, ifree_2, constraints_f_2, constraints_f_cp
end
    
atoms_2, ifree_2, constraints_f_2, constraints_f_cp = test(atoms, ifree, constraints_f)

@show ifree == ifree_2 # shows true
@show constraints_f == constraints_f_2 # shows false
@show constraints_f == constraints_f_cp # shows true
@show constraints_f.ifree == constraints_f_2.ifree # shows true 
@show constraints_f.ifree == constraints_f_cp.ifree # shows true  
```

**Comment by jameskermode** [comment]
I think this may be todo with references vs. copies of arrays?

**Comment by lifelemons** [comment]
I thought that too, but other objects seem to equate fine if generated within a function. Is there something unique/different with FixedCell()?

**Comment by lifelemons** [comment]
Just tested
`@show atoms == atoms_2` and it shows false
I guess it a general thing dependent on the object

**Comment by jameskermode** [comment]
I don't know how equality of type instances is done in Julia, but suspect it might be like `atoms is atoms_2` in Python, i.e. only true if they point to the same object in memory.

**Comment by lifelemons** [comment]
Yeah, seems to be the case, thanks.

**Comment by cortner** [comment]
Should this be changed? We can of course overload ==

**Comment by cortner** [comment]
Maybe best to wait for the pure Julia rewrite though . . .

**Comment by cortner** [comment]
in the `jatoms` branch `==` is overloaded:
```Julia
using JuLIP
atoms = bulk(:Si, pbc=false)
ifree = [1]
constraints_f = FixedCell(atoms, free=ifree)
function test(atoms, ifree, constraints_f)
    atoms_2 = bulk(:Si, pbc=false)
    ifree_2 = [1] # ifree
    constraints_f_2 = FixedCell(atoms_2, free=ifree_2)
    constraints_f_cp = constraints_f
    return atoms_2, ifree_2, constraints_f_2, constraints_f_cp
end
atoms_2, ifree_2, constraints_f_2, constraints_f_cp = test(atoms, ifree, constraints_f)
atoms_2 == atoms   # => true 
```
