### ISSUE TITLE
Split into Smaller Packages

### ISSUE THREAD

**Issue by cortner** [libAtoms/JuLIP.jl#91]
@jameskermode @gabor1  After rewriting the neighbour list in pure Julia, see [NeighbourLists.jl](https://github.com/cortner/NeighbourLists.jl), I've started to re-implement some iteration protocols, and intend to keep these separate from `JuLIP.jl`. More generally, I'd like to split a few other parts of `JuLIP`, for example,  

 * the `Atoms` type : that way it can be used from `NeighbourLists.jl` and other packages without needing to import all of `JuLIP`
 * the `ASE` interface

This should simplify development and testing since JuLIP is actually becoming a bit large. It should also make recompilation easier to manage. One could still reexport all of these satellite packages from JuLIP. 

1. Do you have any thoughts on this? 
2. Should all these repositories go into `libatoms` or do you prefer to keep them separate?

**Comment by gabor1** [comment]
I have nothing against splitting up packages, but there should be a "master" package kept that includes all of them. does that make sense? 

I'm happy to keep the repos under libatoms, but if _you_ want them separate, let me know. 

-- Gábor

**Comment by jameskermode** [comment]
I agree with Gabor - small packages are OK, but can lead to a fragmented experience for users which can be frustrating. Metapackages that pull everything in are one solution, but we need good test coverage as well so that we don't develop version incompatibility problems.

**Comment by cortner** [comment]
My intention was that JuLIP would still pull everything together

**Comment by cortner** [comment]
I got some advise from other Julia contributors and the condensus seems to be that it is maybe not worth it. So I might let this go, or at least I'll proceed much more cautiously . . .
