### ISSUE TITLE
setup for two types of atoms

### ISSUE THREAD

**Issue by git4lei** [libAtoms/JuLIP.jl#93]
It would be great to have an example for a configuration with multiple types of atoms. This would be very useful for complex crystals, alloys, disordered materials etc., since otherwise all the other machinery (potentials, energy minimization, etc.) are already available.

Lei

**Comment by cortner** [comment]
Thank you - do you have a reference for a simple analytical EAM model for such a situation? Otherwise it is maybe time to implement EAM properly.

**Comment by git4lei** [comment]
For metallic glass composed of Cu and Zr, a tabular form of EAM is used in LAMMPS, but that is probably a bit complicated.
https://sites.google.com/site/eampotentials/Home/CuZr <https://sites.google.com/site/eampotentials/Home/CuZr>

For granular materials, I think people just use nonlinear or even linear spring models, for example, formula (1) at page 3 of the attached paper.


Also, in both areas, Lenard-Jones potentials are widely used for qualitative predications, for example, 
http://www-wales.ch.cam.ac.uk/pdf/PRB.64.184201.2001.pdf <http://www-wales.ch.cam.ac.uk/pdf/PRB.64.184201.2001.pdf>

Best regards,
Lei

**Comment by cortner** [comment]
> For metallic glass . . .

I'm not at all against implementing multi-component EAM. It should not be very difficult. If you are willing to help a bit then it could actually be fairly quick as well - otherwise it depends on when I find the time. 

> For granular materials, I think people just use nonlinear or even linear spring models, for example, formula (1) at page 3 of the attached paper.

this should be straightforward. I'll think about it, probably I'll put it into examples rather than core JuLIP though. What do you think?

**Comment by cortner** [comment]
> > For metallic glass . . .

> I'm not at all against implementing multi-component EAM. It should not be very difficult. If you are willing to help a bit then it could actually be fairly quick as well - otherwise it depends on when I find the time. 

Basically, I'd need somebody to figure out how to correctly load multi-component EAM files. The rest is fairly quick and easy to do in JuLIP.

**Comment by cortner** [comment]
@git4lei I've implemented the Wales model and put it into `examples/multi_lj.jl` - I wrote a quick test, but didn't do anything interesting with it. You can probably easily modify this to implement similar code with pair potentials - and EAM is very similar really.

**Comment by cortner** [comment]
@git4lei if you wanted to have a go at loading multi-component EAM files you could have a look at `read_fs` in `eam.jl`

**Comment by git4lei** [comment]
Thanks a lot! I am setting up my Julia 0.6 and will try the test as soon as possible.

**Comment by git4lei** [comment]
It works on my laptop now, we will try to adapt to other pair potentials.

**Comment by cortner** [comment]
If you don’t need multi-EAM for now you could close this? We can look at that at a later time.

**Comment by git4lei** [comment]
Yes, we can look at multi-EAM later. Thanks a lot!

**Comment by git4lei** [comment]
Hi Christoph, how does C2Shift(r) work? I suppose that introduces a cutoff at r, but it appears not...

Lei

**Comment by cortner** [comment]
If not then there is a bug - can you explain?

On 23 Mar 2018, 10:28 +0100, git4lei <notifications@github.com>, wrote:
Hi Christoph, how does C2Shift(r) work? I suppose that introduces a cutoff at r, but it appears not...

Lei

**Comment by git4lei** [comment]
I tried to write a spring potential as your example code MLJ.jl in herz.jl. However, when I plot the potential, I got essentially zero. That is why I’m puzzling.

Also, I cannot even run MLJ.jl today, I got the following error which might comes from your recent update since I can run the code previously, 

Many thanks, 
Lei

---------------------------
using JuLIP
using JuLIP.Potentials: pairs
import JuLIP: energy, forces, cutoff

INFO: Precompiling module JuLIP.
ERROR: LoadError: LoadError: LoadError: UndefVarError: PairList not defined
Stacktrace:
 [1] include_from_node1(::String) at ./loading.jl:576
 [2] include(::String) at ./sysimg.jl:14
 [3] include_from_node1(::String) at ./loading.jl:576
 [4] include(::String) at ./sysimg.jl:14
 [5] include_from_node1(::String) at ./loading.jl:576
 [6] include(::String) at ./sysimg.jl:14
 [7] anonymous at ./<missing>:2
while loading /Applications/JuliaPro-0.6.2.2.app/Contents/Resources/pkgs-0.6.2.2/v0.6/JuLIP/src/eam.jl, in expression starting on line 239
while loading /Applications/JuliaPro-0.6.2.2.app/Contents/Resources/pkgs-0.6.2.2/v0.6/JuLIP/src/Potentials.jl, in expression starting on line 157
while loading /Applications/JuliaPro-0.6.2.2.app/Contents/Resources/pkgs-0.6.2.2/v0.6/JuLIP/src/JuLIP.jl, in expression starting on line 36

**Comment by cortner** [comment]
that's because a C2-shift of a quadratic is always zero :).

**Comment by cortner** [comment]
if you tell me what you'd like to achieve, then I can make a suggestion.

**Comment by cortner** [comment]
I see that there is no documentation at all for this :); I just added the following:
```
"""
`Shift{ORD}` : a shift-cutoff function

It is not technically a cut-off function but a cut-off operator. Let
`f(r)` with real arguments and range, then
```
g = f * Shift(o, rcut)
```
creates a new function `g(r) = (f(r) - p(r)) * (r < rcut)` where
`p(r)` is a polynomial of order `o` such that all derivatives of `g` up
to order `o` vanish at `r = rcut`. There order must be an integer
between -1 and 2. Choosing `o=-1` creates a Heaviside function.

### Equivalent constructors:
```
HS(r::Float64) = Shift(-1, r)
C0Shift(r::Float64) = Shift(0, r)
C1Shift(r::Float64) = Shift(1, r)
C2Shift(r::Float64) = Shift(2, r)
```

### Example:
```
lj = LennardJones()  # standard lennad-jones potential
V = lj * C2Shift(2.5)
```
Now `V` is a C2-continuous `PairPotential` with support (0, 2.5].
"""
```

**Comment by cortner** [comment]
@git4lei 

> Also, I cannot even run MLJ.jl today, I got the following error which might comes from your recent update since I can run the code previously,

I tried it both on `v0.4.0` and on `master` and on both its works ok for me.

**Comment by git4lei** [comment]
Thanks, indeed I realized this after a second thought. 

Originally I thought to introduce a smooth transition of the quadratic potential since the second order derivative is discontinuous, do you think that is a good thing to do?

**Comment by git4lei** [comment]
after Pkg.update(), it works fine now.

**Comment by git4lei** [comment]
Thanks for the documentation.
